<<<<<<<< HEAD:devices/BuildHat/samples/Properties/AssemblyInfo.cs
========
﻿// <auto-generated />

>>>>>>>> 4031cbea0 (Naming convention change stage 1):devices/At24Cxx2/Properties/AssemblyInfo.cs
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

<<<<<<<< HEAD:devices/BuildHat/samples/Properties/AssemblyInfo.cs
[assembly: AssemblyTitle("Iot.Device.BuildHat.samples")]
========
[assembly: AssemblyTitle("Iot.Device.At24Cxx")]
>>>>>>>> 4031cbea0 (Naming convention change stage 1):devices/At24Cxx2/Properties/AssemblyInfo.cs
[assembly: AssemblyCompany("nanoFramework Contributors")]
[assembly: AssemblyCopyright("Copyright(c).NET Foundation and Contributors")]

[assembly: ComVisible(false)]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
