// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// This is a class added (and should be autogenerated) specifically for nanoFramework.

using System;

namespace Iot.Device.Graphics
{
    /// <summary>
    /// 
    /// </summary>
    public class CharByte
    {
        /// <summary>
        /// A CharByte
        /// </summary>
        /// <param name="cr">a char</param>
        /// <param name="bt">a byte</param>
        public CharByte(char cr, byte bt)
        {
            Cr = cr;
            Bt = bt;
        }

        /// <summary>
        /// The Char
        /// </summary>
        public char Cr { get; set; }
        /// <summary>
        /// The Byte
        /// </summary>
        public byte Bt { get; set; }
    }
}
