// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections;
using System.Text;

namespace Iot.Device.Graphics
{
    /// <summary>
    /// Provides the character encoding for an LCD display.
    /// Instances of this class are generated by <see cref="LcdCharacterEncodingFactory"/>.
    /// </summary>
    public class LcdCharacterEncoding : Encoding
    {
        private readonly DictionaryCharByte _characterMapping;
        private readonly char _unknownLetter;
        // Character pixel maps for characters that will need to be written to the character RAM for this code page
        private readonly ArrayList _extraCharacters;
        private readonly string _cultureName;

        /// <inheritDoc/>
        public override Decoder GetDecoder()
        {
            return GetDecoder();
    }

        /// <summary>
        /// Creates an instance of <see cref="LcdCharacterEncoding"/>.
        /// </summary>
        /// <param name="cultureName">Culture name for this encoding (informational only)</param>
        /// <param name="readOnlyMemoryName">Name of the ROM (hard coded read-only character memory) on the display</param>
        /// <param name="characterMap">The character map to use</param>
        /// <param name="unknownLetter">The character to print when a letter not in the map is found. This letter must be part of the map</param>
        public LcdCharacterEncoding(string cultureName, string readOnlyMemoryName, DictionaryCharByte characterMap, char unknownLetter)
        {
            _cultureName = cultureName;
            _characterMapping = characterMap;
            _unknownLetter = unknownLetter;
            _extraCharacters = new ArrayList();
            AllCharactersSupported = true;
            ReadOnlyMemoryName = readOnlyMemoryName;
            if (!_characterMapping.ContainsKey(unknownLetter))
            {
                throw new ArgumentException($"The replacement letter {unknownLetter} is not part of the character map", nameof(unknownLetter));
            }
        }

        /// <summary>
        /// Creates an instance of <see cref="LcdCharacterEncoding"/>.
        /// </summary>
        /// <param name="cultureName">Culture name for this encoding (informational only)</param>
        /// <param name="readOnlyMemoryName">Name of the ROM (hard coded read-only character memory) on the display</param>
        /// <param name="characterMap">The character map to use</param>
        /// <param name="unknownLetter">The character to print when a letter not in the map is found</param>
        /// <param name="extraCharacters">The pixel map of characters required for this culture but not found in the character ROM</param>
        public LcdCharacterEncoding(string cultureName, string readOnlyMemoryName, DictionaryCharByte characterMap, char unknownLetter, ArrayList extraCharacters)
            : this(cultureName, readOnlyMemoryName, characterMap, unknownLetter)
        {
            _extraCharacters = extraCharacters;
            AllCharactersSupported = true;
        }

        /// <summary>
        /// Always returns true for this class.
        /// </summary>
        public bool IsSingleByte => true;

        /// <inheritDoc/>
        public string EncodingName => _cultureName;

        /// <summary>
        /// The list of pixel maps for extra characters that are required for this culture.
        /// </summary>
        public virtual ArrayList ExtraCharacters => _extraCharacters;

        /// <summary>
        /// This is internally set to false if we already know that we won't be able to display all required characters
        /// </summary>
        public bool AllCharactersSupported { get; set; }

        /// <summary>
        /// Specified Name of the hardcoded character memory set for which this Encoding is intended. An encoding shall only be loaded to
        /// a matching display.
        /// </summary>
        public string ReadOnlyMemoryName { get; }

        /// <inheritDoc/>
        public int GetByteCount(char[] chars, int index, int count)
        {
            if (index + count > chars.Length || index < 0 || count < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(index), "Index + count must be smaller than array length");
            }

            return count;
        }

        /// <inheritDoc/>
        public int GetBytes(char[] chars, int charIndex, int charCount, ArrayList bytes, int byteIndex)
        {
            for (int i = 0; i < charCount; i++)
            {
                byte b;
                if (_characterMapping is null)
                {
                    bytes[byteIndex] = (byte)chars[charIndex];
                }
                else if (_characterMapping.TryGetValue(chars[charIndex], out b))
                {
                    bytes[byteIndex] = b;
                }
                else
                {
                    //bytes[byteIndex] = _characterMapping[_unknownLetter];
                    throw new Exception("TODO!!! - Convert unknown letter!");
                }

                byteIndex++;
                charIndex++;
            }

            return charCount;
        }

        /// <inheritDoc/>
        public int GetCharCount(byte[] bytes, int index, int count) => Math.Min(bytes.Length, count);

        /// <summary>
        /// Reverse mapping is not supported for this encoding.
        /// </summary>
        public int GetChars(byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex) => throw new NotSupportedException("Reverse conversion not supported");

        /// <inheritDoc/>
        // This encoder always does a 1:1 mapping
        public int GetMaxByteCount(int charCount) => charCount;

        /// <inheritDoc/>
        public int GetMaxCharCount(int byteCount) => byteCount;
    }
}
